# Generated by Django 3.2.5 on 2022-05-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
