# Generated by Django 3.2.5 on 2022-05-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220512_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
    ]
